// Mocks generated by Mockito 5.4.6 from annotations
// in provisioning_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flutter/foundation.dart' as _i14;
import 'package:flutter_appauth/flutter_appauth.dart' as _i3;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:logger/logger.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:provisioning_app/auth/auth_service.dart' as _i5;
import 'package:provisioning_app/data/repositories/viam_app_repository.dart'
    as _i16;
import 'package:provisioning_app/data/services/shared_preferences_service.dart'
    as _i15;
import 'package:viam_sdk/protos/app/packages.dart' as _i13;
import 'package:viam_sdk/src/app/app.dart' as _i7;
import 'package:viam_sdk/src/app/billing.dart' as _i8;
import 'package:viam_sdk/src/app/permissions.dart' as _i11;
import 'package:viam_sdk/src/gen/app/v1/app.pbgrpc.dart' as _i2;
import 'package:viam_sdk/src/gen/common/v1/common.pb.dart' as _i12;
import 'package:viam_sdk/viam_sdk.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrganization_0 extends _i1.SmartFake implements _i2.Organization {
  _FakeOrganization_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListOrganizationMembersResponse_1 extends _i1.SmartFake
    implements _i2.ListOrganizationMembersResponse {
  _FakeListOrganizationMembersResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeOrganizationInvite_2 extends _i1.SmartFake
    implements _i2.OrganizationInvite {
  _FakeOrganizationInvite_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocation_3 extends _i1.SmartFake implements _i2.Location {
  _FakeLocation_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationAuth_4 extends _i1.SmartFake implements _i2.LocationAuth {
  _FakeLocationAuth_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRobot_5 extends _i1.SmartFake implements _i2.Robot {
  _FakeRobot_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRobotPart_6 extends _i1.SmartFake implements _i2.RobotPart {
  _FakeRobotPart_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetRobotPartLogsResponse_7 extends _i1.SmartFake
    implements _i2.GetRobotPartLogsResponse {
  _FakeGetRobotPartLogsResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFragment_8 extends _i1.SmartFake implements _i2.Fragment {
  _FakeFragment_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegistryItem_9 extends _i1.SmartFake implements _i2.RegistryItem {
  _FakeRegistryItem_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateModuleResponse_10 extends _i1.SmartFake
    implements _i2.CreateModuleResponse {
  _FakeCreateModuleResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeModule_11 extends _i1.SmartFake implements _i2.Module {
  _FakeModule_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateKeyResponse_12 extends _i1.SmartFake
    implements _i2.CreateKeyResponse {
  _FakeCreateKeyResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRotateKeyResponse_13 extends _i1.SmartFake
    implements _i2.RotateKeyResponse {
  _FakeRotateKeyResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateKeyFromExistingKeyAuthorizationsResponse_14
    extends _i1.SmartFake
    implements _i2.CreateKeyFromExistingKeyAuthorizationsResponse {
  _FakeCreateKeyFromExistingKeyAuthorizationsResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGetOrganizationMetadataResponse_15 extends _i1.SmartFake
    implements _i2.GetOrganizationMetadataResponse {
  _FakeGetOrganizationMetadataResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGetLocationMetadataResponse_16 extends _i1.SmartFake
    implements _i2.GetLocationMetadataResponse {
  _FakeGetLocationMetadataResponse_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGetRobotMetadataResponse_17 extends _i1.SmartFake
    implements _i2.GetRobotMetadataResponse {
  _FakeGetRobotMetadataResponse_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetRobotPartMetadataResponse_18 extends _i1.SmartFake
    implements _i2.GetRobotPartMetadataResponse {
  _FakeGetRobotPartMetadataResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeFlutterAppAuth_19 extends _i1.SmartFake
    implements _i3.FlutterAppAuth {
  _FakeFlutterAppAuth_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_20 extends _i1.SmartFake
    implements _i4.FlutterSecureStorage {
  _FakeFlutterSecureStorage_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeViamUserProfile_21 extends _i1.SmartFake
    implements _i5.ViamUserProfile {
  _FakeViamUserProfile_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeViam_22 extends _i1.SmartFake implements _i6.Viam {
  _FakeViam_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthorizationTokenResponse_23 extends _i1.SmartFake
    implements _i3.AuthorizationTokenResponse {
  _FakeAuthorizationTokenResponse_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthorizationResponse_24 extends _i1.SmartFake
    implements _i3.AuthorizationResponse {
  _FakeAuthorizationResponse_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTokenResponse_25 extends _i1.SmartFake implements _i3.TokenResponse {
  _FakeTokenResponse_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEndSessionResponse_26 extends _i1.SmartFake
    implements _i3.EndSessionResponse {
  _FakeEndSessionResponse_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_27 extends _i1.SmartFake implements _i4.IOSOptions {
  _FakeIOSOptions_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_28 extends _i1.SmartFake
    implements _i4.AndroidOptions {
  _FakeAndroidOptions_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_29 extends _i1.SmartFake implements _i4.LinuxOptions {
  _FakeLinuxOptions_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_30 extends _i1.SmartFake
    implements _i4.WindowsOptions {
  _FakeWindowsOptions_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_31 extends _i1.SmartFake implements _i4.WebOptions {
  _FakeWebOptions_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_32 extends _i1.SmartFake implements _i4.MacOsOptions {
  _FakeMacOsOptions_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppClient_33 extends _i1.SmartFake implements _i7.AppClient {
  _FakeAppClient_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppRobotClient_34 extends _i1.SmartFake
    implements _i6.AppRobotClient {
  _FakeAppRobotClient_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBillingClient_35 extends _i1.SmartFake implements _i8.BillingClient {
  _FakeBillingClient_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDataClient_36 extends _i1.SmartFake implements _i6.DataClient {
  _FakeDataClient_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProvisioningClient_37 extends _i1.SmartFake
    implements _i6.ProvisioningClient {
  _FakeProvisioningClient_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRobotClient_38 extends _i1.SmartFake implements _i6.RobotClient {
  _FakeRobotClient_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_39<T1> extends _i1.SmartFake implements _i9.Future<T1> {
  _FakeFuture_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppClient extends _i1.Mock implements _i7.AppClient {
  MockAppClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i2.LocationSummary>> listMachineSummaries(
    String? organizationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listMachineSummaries, [organizationId]),
            returnValue: _i9.Future<List<_i2.LocationSummary>>.value(
              <_i2.LocationSummary>[],
            ),
          )
          as _i9.Future<List<_i2.LocationSummary>>);

  @override
  _i9.Future<String> getUserIdByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdByEmail, [email]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getUserIdByEmail, [email]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<_i2.Organization> createOrganization(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createOrganization, [name]),
            returnValue: _i9.Future<_i2.Organization>.value(
              _FakeOrganization_0(
                this,
                Invocation.method(#createOrganization, [name]),
              ),
            ),
          )
          as _i9.Future<_i2.Organization>);

  @override
  _i9.Future<List<_i2.Organization>> listOrganizations() =>
      (super.noSuchMethod(
            Invocation.method(#listOrganizations, []),
            returnValue: _i9.Future<List<_i2.Organization>>.value(
              <_i2.Organization>[],
            ),
          )
          as _i9.Future<List<_i2.Organization>>);

  @override
  _i9.Future<List<_i2.OrganizationIdentity>>
  getOrganizationsWithAccessToLocation(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganizationsWithAccessToLocation, [
              locationId,
            ]),
            returnValue: _i9.Future<List<_i2.OrganizationIdentity>>.value(
              <_i2.OrganizationIdentity>[],
            ),
          )
          as _i9.Future<List<_i2.OrganizationIdentity>>);

  @override
  _i9.Future<List<_i2.OrgDetails>> listOrganizationsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#listOrganizationsByUser, [userId]),
            returnValue: _i9.Future<List<_i2.OrgDetails>>.value(
              <_i2.OrgDetails>[],
            ),
          )
          as _i9.Future<List<_i2.OrgDetails>>);

  @override
  _i9.Future<_i2.Organization> getOrganization(String? organizationId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganization, [organizationId]),
            returnValue: _i9.Future<_i2.Organization>.value(
              _FakeOrganization_0(
                this,
                Invocation.method(#getOrganization, [organizationId]),
              ),
            ),
          )
          as _i9.Future<_i2.Organization>);

  @override
  _i9.Future<bool> getOrganizationNamespaceAvailability(
    String? publicNamespace,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganizationNamespaceAvailability, [
              publicNamespace,
            ]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i2.Organization> updateOrganization(
    String? organizationId, {
    String? name,
    String? publicNamespace,
    String? region,
    String? cid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateOrganization,
              [organizationId],
              {
                #name: name,
                #publicNamespace: publicNamespace,
                #region: region,
                #cid: cid,
              },
            ),
            returnValue: _i9.Future<_i2.Organization>.value(
              _FakeOrganization_0(
                this,
                Invocation.method(
                  #updateOrganization,
                  [organizationId],
                  {
                    #name: name,
                    #publicNamespace: publicNamespace,
                    #region: region,
                    #cid: cid,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Organization>);

  @override
  _i9.Future<void> deleteOrganization(String? organizationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrganization, [organizationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.ListOrganizationMembersResponse> listOrganizationMembers(
    String? organizationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listOrganizationMembers, [organizationId]),
            returnValue: _i9.Future<_i2.ListOrganizationMembersResponse>.value(
              _FakeListOrganizationMembersResponse_1(
                this,
                Invocation.method(#listOrganizationMembers, [organizationId]),
              ),
            ),
          )
          as _i9.Future<_i2.ListOrganizationMembersResponse>);

  @override
  _i9.Future<_i2.OrganizationInvite> createOrganizationInvite(
    String? organizationId,
    String? email,
    List<_i11.ViamAuthorization>? authorizations, {
    bool? sendEmailInvite = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createOrganizationInvite,
              [organizationId, email, authorizations],
              {#sendEmailInvite: sendEmailInvite},
            ),
            returnValue: _i9.Future<_i2.OrganizationInvite>.value(
              _FakeOrganizationInvite_2(
                this,
                Invocation.method(
                  #createOrganizationInvite,
                  [organizationId, email, authorizations],
                  {#sendEmailInvite: sendEmailInvite},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.OrganizationInvite>);

  @override
  _i9.Future<_i2.OrganizationInvite> updateOrganizationInviteAuthorizations(
    String? organizationId,
    String? email,
    List<_i11.ViamAuthorization>? addAuthorizations,
    List<_i11.ViamAuthorization>? removeAuthorizations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrganizationInviteAuthorizations, [
              organizationId,
              email,
              addAuthorizations,
              removeAuthorizations,
            ]),
            returnValue: _i9.Future<_i2.OrganizationInvite>.value(
              _FakeOrganizationInvite_2(
                this,
                Invocation.method(#updateOrganizationInviteAuthorizations, [
                  organizationId,
                  email,
                  addAuthorizations,
                  removeAuthorizations,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.OrganizationInvite>);

  @override
  _i9.Future<void> deleteOrganizationMember(
    String? organizationId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrganizationMember, [
              organizationId,
              userId,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteOrganizationInvite(
    String? organizationId,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrganizationInvite, [
              organizationId,
              email,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.OrganizationInvite> resendOrganizationInvite(
    String? organizationId,
    String? email, {
    bool? sendEmailInvite = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resendOrganizationInvite,
              [organizationId, email],
              {#sendEmailInvite: sendEmailInvite},
            ),
            returnValue: _i9.Future<_i2.OrganizationInvite>.value(
              _FakeOrganizationInvite_2(
                this,
                Invocation.method(
                  #resendOrganizationInvite,
                  [organizationId, email],
                  {#sendEmailInvite: sendEmailInvite},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.OrganizationInvite>);

  @override
  _i9.Future<_i2.Location> createLocation(
    String? organizationId,
    String? name, {
    String? parentLocationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createLocation,
              [organizationId, name],
              {#parentLocationId: parentLocationId},
            ),
            returnValue: _i9.Future<_i2.Location>.value(
              _FakeLocation_3(
                this,
                Invocation.method(
                  #createLocation,
                  [organizationId, name],
                  {#parentLocationId: parentLocationId},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Location>);

  @override
  _i9.Future<_i2.Location> getLocation(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocation, [locationId]),
            returnValue: _i9.Future<_i2.Location>.value(
              _FakeLocation_3(
                this,
                Invocation.method(#getLocation, [locationId]),
              ),
            ),
          )
          as _i9.Future<_i2.Location>);

  @override
  _i9.Future<_i2.Location> updateLocation(
    String? locationId, {
    String? name,
    String? parentLocationId,
    String? region,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateLocation,
              [locationId],
              {
                #name: name,
                #parentLocationId: parentLocationId,
                #region: region,
              },
            ),
            returnValue: _i9.Future<_i2.Location>.value(
              _FakeLocation_3(
                this,
                Invocation.method(
                  #updateLocation,
                  [locationId],
                  {
                    #name: name,
                    #parentLocationId: parentLocationId,
                    #region: region,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Location>);

  @override
  _i9.Future<void> deleteLocation(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocation, [locationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.Location>> listLocations(String? organizationId) =>
      (super.noSuchMethod(
            Invocation.method(#listLocations, [organizationId]),
            returnValue: _i9.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i9.Future<List<_i2.Location>>);

  @override
  _i9.Future<void> shareLocation(String? locationId, String? organizationId) =>
      (super.noSuchMethod(
            Invocation.method(#shareLocation, [locationId, organizationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> unshareLocation(
    String? locationId,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unshareLocation, [locationId, organizationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.LocationAuth> locationAuth(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#locationAuth, [locationId]),
            returnValue: _i9.Future<_i2.LocationAuth>.value(
              _FakeLocationAuth_4(
                this,
                Invocation.method(#locationAuth, [locationId]),
              ),
            ),
          )
          as _i9.Future<_i2.LocationAuth>);

  @override
  _i9.Future<_i2.LocationAuth> createLocationSecret(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#createLocationSecret, [locationId]),
            returnValue: _i9.Future<_i2.LocationAuth>.value(
              _FakeLocationAuth_4(
                this,
                Invocation.method(#createLocationSecret, [locationId]),
              ),
            ),
          )
          as _i9.Future<_i2.LocationAuth>);

  @override
  _i9.Future<void> deleteLocationSecret(String? locationId, String? secretId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocationSecret, [locationId, secretId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.Robot> getRobot(String? robotId) =>
      (super.noSuchMethod(
            Invocation.method(#getRobot, [robotId]),
            returnValue: _i9.Future<_i2.Robot>.value(
              _FakeRobot_5(this, Invocation.method(#getRobot, [robotId])),
            ),
          )
          as _i9.Future<_i2.Robot>);

  @override
  _i9.Future<List<_i2.RoverRentalRobot>> getRoverRentalRobots(String? orgId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoverRentalRobots, [orgId]),
            returnValue: _i9.Future<List<_i2.RoverRentalRobot>>.value(
              <_i2.RoverRentalRobot>[],
            ),
          )
          as _i9.Future<List<_i2.RoverRentalRobot>>);

  @override
  _i9.Future<List<_i2.RobotPart>> listRobotParts(String? robotId) =>
      (super.noSuchMethod(
            Invocation.method(#listRobotParts, [robotId]),
            returnValue: _i9.Future<List<_i2.RobotPart>>.value(
              <_i2.RobotPart>[],
            ),
          )
          as _i9.Future<List<_i2.RobotPart>>);

  @override
  _i9.Future<_i2.RobotPart> getRobotPart(String? partId) =>
      (super.noSuchMethod(
            Invocation.method(#getRobotPart, [partId]),
            returnValue: _i9.Future<_i2.RobotPart>.value(
              _FakeRobotPart_6(
                this,
                Invocation.method(#getRobotPart, [partId]),
              ),
            ),
          )
          as _i9.Future<_i2.RobotPart>);

  @override
  _i9.Future<_i2.GetRobotPartLogsResponse> getLogs(
    String? partId, {
    String? filter,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLogs,
              [partId],
              {#filter: filter, #pageToken: pageToken},
            ),
            returnValue: _i9.Future<_i2.GetRobotPartLogsResponse>.value(
              _FakeGetRobotPartLogsResponse_7(
                this,
                Invocation.method(
                  #getLogs,
                  [partId],
                  {#filter: filter, #pageToken: pageToken},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.GetRobotPartLogsResponse>);

  @override
  _i9.Stream<List<_i12.LogEntry>> tailLogs(
    String? partId, {
    bool? errorsOnly = false,
    String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #tailLogs,
              [partId],
              {#errorsOnly: errorsOnly, #filter: filter},
            ),
            returnValue: _i9.Stream<List<_i12.LogEntry>>.empty(),
          )
          as _i9.Stream<List<_i12.LogEntry>>);

  @override
  _i9.Future<List<_i2.RobotPartHistoryEntry>> getRobotPartHistory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRobotPartHistory, [id]),
            returnValue: _i9.Future<List<_i2.RobotPartHistoryEntry>>.value(
              <_i2.RobotPartHistoryEntry>[],
            ),
          )
          as _i9.Future<List<_i2.RobotPartHistoryEntry>>);

  @override
  _i9.Future<_i2.RobotPart> updateRobotPart(
    String? partId,
    String? name,
    Map<String, dynamic>? robotConfig, {
    DateTime? lastKnownUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRobotPart,
              [partId, name, robotConfig],
              {#lastKnownUpdate: lastKnownUpdate},
            ),
            returnValue: _i9.Future<_i2.RobotPart>.value(
              _FakeRobotPart_6(
                this,
                Invocation.method(
                  #updateRobotPart,
                  [partId, name, robotConfig],
                  {#lastKnownUpdate: lastKnownUpdate},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.RobotPart>);

  @override
  _i9.Future<String> newRobotPart(String? robotId, String? partName) =>
      (super.noSuchMethod(
            Invocation.method(#newRobotPart, [robotId, partName]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#newRobotPart, [robotId, partName]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> deleteRobotPart(String? partId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRobotPart, [partId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.APIKeyWithAuthorizations>> getRobotApiKeys(
    String? robotId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRobotApiKeys, [robotId]),
            returnValue: _i9.Future<List<_i2.APIKeyWithAuthorizations>>.value(
              <_i2.APIKeyWithAuthorizations>[],
            ),
          )
          as _i9.Future<List<_i2.APIKeyWithAuthorizations>>);

  @override
  _i9.Future<void> markPartAsMain(String? partId) =>
      (super.noSuchMethod(
            Invocation.method(#markPartAsMain, [partId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> markPartForRestart(String? partId) =>
      (super.noSuchMethod(
            Invocation.method(#markPartForRestart, [partId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.RobotPart> createRobotPartSecret(String? partId) =>
      (super.noSuchMethod(
            Invocation.method(#createRobotPartSecret, [partId]),
            returnValue: _i9.Future<_i2.RobotPart>.value(
              _FakeRobotPart_6(
                this,
                Invocation.method(#createRobotPartSecret, [partId]),
              ),
            ),
          )
          as _i9.Future<_i2.RobotPart>);

  @override
  _i9.Future<void> deleteRobotPartSecret(String? partId, String? secretId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRobotPartSecret, [partId, secretId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.Robot>> listRobots(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#listRobots, [locationId]),
            returnValue: _i9.Future<List<_i2.Robot>>.value(<_i2.Robot>[]),
          )
          as _i9.Future<List<_i2.Robot>>);

  @override
  _i9.Future<String> newMachine(String? name, String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#newMachine, [name, locationId]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#newMachine, [name, locationId]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<_i2.Robot> updateRobot(
    String? id,
    String? name,
    String? location,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRobot, [id, name, location]),
            returnValue: _i9.Future<_i2.Robot>.value(
              _FakeRobot_5(
                this,
                Invocation.method(#updateRobot, [id, name, location]),
              ),
            ),
          )
          as _i9.Future<_i2.Robot>);

  @override
  _i9.Future<void> deleteRobot(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRobot, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.Fragment>> listFragments(
    String? organizationId,
    bool? showPublic, {
    List<_i2.FragmentVisibility>? fragmentVisibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listFragments,
              [organizationId, showPublic],
              {#fragmentVisibility: fragmentVisibility},
            ),
            returnValue: _i9.Future<List<_i2.Fragment>>.value(<_i2.Fragment>[]),
          )
          as _i9.Future<List<_i2.Fragment>>);

  @override
  _i9.Future<_i2.Fragment> getFragment(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFragment, [id]),
            returnValue: _i9.Future<_i2.Fragment>.value(
              _FakeFragment_8(this, Invocation.method(#getFragment, [id])),
            ),
          )
          as _i9.Future<_i2.Fragment>);

  @override
  _i9.Future<_i2.Fragment> createFragment(
    String? name,
    Map<String, dynamic>? config,
    String? organizationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createFragment, [name, config, organizationId]),
            returnValue: _i9.Future<_i2.Fragment>.value(
              _FakeFragment_8(
                this,
                Invocation.method(#createFragment, [
                  name,
                  config,
                  organizationId,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.Fragment>);

  @override
  _i9.Future<_i2.Fragment> updateFragment(
    String? id,
    String? name,
    Map<String, dynamic>? config, {
    bool? public,
    _i2.FragmentVisibility? visibility,
    DateTime? lastKnownUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateFragment,
              [id, name, config],
              {
                #public: public,
                #visibility: visibility,
                #lastKnownUpdate: lastKnownUpdate,
              },
            ),
            returnValue: _i9.Future<_i2.Fragment>.value(
              _FakeFragment_8(
                this,
                Invocation.method(
                  #updateFragment,
                  [id, name, config],
                  {
                    #public: public,
                    #visibility: visibility,
                    #lastKnownUpdate: lastKnownUpdate,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Fragment>);

  @override
  _i9.Future<void> deleteFragment(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFragment, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> addRole(_i11.ViamAuthorization? authorization) =>
      (super.noSuchMethod(
            Invocation.method(#addRole, [authorization]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeRole(_i11.ViamAuthorization? authorization) =>
      (super.noSuchMethod(
            Invocation.method(#removeRole, [authorization]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> changeRole(
    _i11.ViamAuthorization? oldAuthorization,
    _i11.ViamAuthorization? newAuthorization,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeRole, [
              oldAuthorization,
              newAuthorization,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.Authorization>> listAuthorizations(
    String? organizationId, {
    List<String>? resourceIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listAuthorizations,
              [organizationId],
              {#resourceIds: resourceIds},
            ),
            returnValue: _i9.Future<List<_i2.Authorization>>.value(
              <_i2.Authorization>[],
            ),
          )
          as _i9.Future<List<_i2.Authorization>>);

  @override
  _i9.Future<List<_i11.Permission>> checkPermissions(
    _i11.ResourceType? resourceType,
    String? resourceId,
    List<_i11.Permission>? permissions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkPermissions, [
              resourceType,
              resourceId,
              permissions,
            ]),
            returnValue: _i9.Future<List<_i11.Permission>>.value(
              <_i11.Permission>[],
            ),
          )
          as _i9.Future<List<_i11.Permission>>);

  @override
  _i9.Future<_i2.RegistryItem> getRegistryItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getRegistryItem, [itemId]),
            returnValue: _i9.Future<_i2.RegistryItem>.value(
              _FakeRegistryItem_9(
                this,
                Invocation.method(#getRegistryItem, [itemId]),
              ),
            ),
          )
          as _i9.Future<_i2.RegistryItem>);

  @override
  _i9.Future<void> createRegistryItem(
    String? organizationId,
    String? name,
    _i13.PackageType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRegistryItem, [
              organizationId,
              name,
              type,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateRegistryItem(
    String? itemId,
    _i13.PackageType? type,
    String? description,
    _i2.Visibility? visibility,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRegistryItem, [
              itemId,
              type,
              description,
              visibility,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.RegistryItem>> listRegistryItems(
    List<_i13.PackageType>? types,
    List<_i2.Visibility>? visibilities,
    List<String>? platforms,
    List<_i2.RegistryItemStatus>? statuses, {
    String? organizationId,
    String? searchTerm,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listRegistryItems,
              [types, visibilities, platforms, statuses],
              {
                #organizationId: organizationId,
                #searchTerm: searchTerm,
                #pageToken: pageToken,
              },
            ),
            returnValue: _i9.Future<List<_i2.RegistryItem>>.value(
              <_i2.RegistryItem>[],
            ),
          )
          as _i9.Future<List<_i2.RegistryItem>>);

  @override
  _i9.Future<void> deleteRegistryItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRegistryItem, [itemId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.CreateModuleResponse> createModule(
    String? organizationId,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createModule, [organizationId, name]),
            returnValue: _i9.Future<_i2.CreateModuleResponse>.value(
              _FakeCreateModuleResponse_10(
                this,
                Invocation.method(#createModule, [organizationId, name]),
              ),
            ),
          )
          as _i9.Future<_i2.CreateModuleResponse>);

  @override
  _i9.Future<String> updateModule(
    String? moduleId,
    _i2.Visibility? visibility,
    String? url,
    String? description,
    List<_i2.Model>? models,
    String? entrypoint,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateModule, [
              moduleId,
              visibility,
              url,
              description,
              models,
              entrypoint,
            ]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#updateModule, [
                  moduleId,
                  visibility,
                  url,
                  description,
                  models,
                  entrypoint,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<String> uploadModuleFile(
    _i2.ModuleFileInfo? moduleFileInfo,
    List<int>? file,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadModuleFile, [moduleFileInfo, file]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#uploadModuleFile, [moduleFileInfo, file]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<_i2.Module> getModule(String? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#getModule, [moduleId]),
            returnValue: _i9.Future<_i2.Module>.value(
              _FakeModule_11(this, Invocation.method(#getModule, [moduleId])),
            ),
          )
          as _i9.Future<_i2.Module>);

  @override
  _i9.Future<List<_i2.Module>> listModules(String? organizationId) =>
      (super.noSuchMethod(
            Invocation.method(#listModules, [organizationId]),
            returnValue: _i9.Future<List<_i2.Module>>.value(<_i2.Module>[]),
          )
          as _i9.Future<List<_i2.Module>>);

  @override
  _i9.Future<_i2.CreateKeyResponse> createKey(
    List<_i11.ViamAuthorization>? authorizations,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createKey, [authorizations, name]),
            returnValue: _i9.Future<_i2.CreateKeyResponse>.value(
              _FakeCreateKeyResponse_12(
                this,
                Invocation.method(#createKey, [authorizations, name]),
              ),
            ),
          )
          as _i9.Future<_i2.CreateKeyResponse>);

  @override
  _i9.Future<void> deleteKey(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKey, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.APIKeyWithAuthorizations>> listKeys(String? orgId) =>
      (super.noSuchMethod(
            Invocation.method(#listKeys, [orgId]),
            returnValue: _i9.Future<List<_i2.APIKeyWithAuthorizations>>.value(
              <_i2.APIKeyWithAuthorizations>[],
            ),
          )
          as _i9.Future<List<_i2.APIKeyWithAuthorizations>>);

  @override
  _i9.Future<_i2.RotateKeyResponse> rotateKey(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#rotateKey, [id]),
            returnValue: _i9.Future<_i2.RotateKeyResponse>.value(
              _FakeRotateKeyResponse_13(
                this,
                Invocation.method(#rotateKey, [id]),
              ),
            ),
          )
          as _i9.Future<_i2.RotateKeyResponse>);

  @override
  _i9.Future<_i2.CreateKeyFromExistingKeyAuthorizationsResponse>
  createKeyFromExistingKeyAuthorizations(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#createKeyFromExistingKeyAuthorizations, [id]),
            returnValue: _i9.Future<
              _i2.CreateKeyFromExistingKeyAuthorizationsResponse
            >.value(
              _FakeCreateKeyFromExistingKeyAuthorizationsResponse_14(
                this,
                Invocation.method(#createKeyFromExistingKeyAuthorizations, [
                  id,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.CreateKeyFromExistingKeyAuthorizationsResponse>);

  @override
  _i9.Future<_i2.GetOrganizationMetadataResponse> getOrganizationMetadata(
    String? organizationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganizationMetadata, [organizationId]),
            returnValue: _i9.Future<_i2.GetOrganizationMetadataResponse>.value(
              _FakeGetOrganizationMetadataResponse_15(
                this,
                Invocation.method(#getOrganizationMetadata, [organizationId]),
              ),
            ),
          )
          as _i9.Future<_i2.GetOrganizationMetadataResponse>);

  @override
  _i9.Future<void> updateOrganizationMetadata(
    String? organizationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrganizationMetadata, [
              organizationId,
              data,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.GetLocationMetadataResponse> getLocationMetadata(
    String? locationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationMetadata, [locationId]),
            returnValue: _i9.Future<_i2.GetLocationMetadataResponse>.value(
              _FakeGetLocationMetadataResponse_16(
                this,
                Invocation.method(#getLocationMetadata, [locationId]),
              ),
            ),
          )
          as _i9.Future<_i2.GetLocationMetadataResponse>);

  @override
  _i9.Future<void> updateLocationMetadata(
    String? locationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocationMetadata, [locationId, data]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.GetRobotMetadataResponse> getRobotMetadata(String? robotId) =>
      (super.noSuchMethod(
            Invocation.method(#getRobotMetadata, [robotId]),
            returnValue: _i9.Future<_i2.GetRobotMetadataResponse>.value(
              _FakeGetRobotMetadataResponse_17(
                this,
                Invocation.method(#getRobotMetadata, [robotId]),
              ),
            ),
          )
          as _i9.Future<_i2.GetRobotMetadataResponse>);

  @override
  _i9.Future<void> updateRobotMetadata(
    String? robotId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRobotMetadata, [robotId, data]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.GetRobotPartMetadataResponse> getRobotPartMetadata(
    String? robotPartId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRobotPartMetadata, [robotPartId]),
            returnValue: _i9.Future<_i2.GetRobotPartMetadataResponse>.value(
              _FakeGetRobotPartMetadataResponse_18(
                this,
                Invocation.method(#getRobotPartMetadata, [robotPartId]),
              ),
            ),
          )
          as _i9.Future<_i2.GetRobotPartMetadataResponse>);

  @override
  _i9.Future<void> updateRobotPartMetadata(
    String? robotPartId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRobotPartMetadata, [robotPartId, data]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FlutterAppAuth get appAuth =>
      (super.noSuchMethod(
            Invocation.getter(#appAuth),
            returnValue: _FakeFlutterAppAuth_19(
              this,
              Invocation.getter(#appAuth),
            ),
          )
          as _i3.FlutterAppAuth);

  @override
  _i4.FlutterSecureStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeFlutterSecureStorage_20(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i4.FlutterSecureStorage);

  @override
  bool get isConnectionError =>
      (super.noSuchMethod(
            Invocation.getter(#isConnectionError),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Future<String> get accessToken =>
      (super.noSuchMethod(
            Invocation.getter(#accessToken),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(this, Invocation.getter(#accessToken)),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<_i5.ViamUserProfile> get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue: _i9.Future<_i5.ViamUserProfile>.value(
              _FakeViamUserProfile_21(this, Invocation.getter(#currentUser)),
            ),
          )
          as _i9.Future<_i5.ViamUserProfile>);

  @override
  _i9.Future<_i6.Viam> get authenticatedViam =>
      (super.noSuchMethod(
            Invocation.getter(#authenticatedViam),
            returnValue: _i9.Future<_i6.Viam>.value(
              _FakeViam_22(this, Invocation.getter(#authenticatedViam)),
            ),
          )
          as _i9.Future<_i6.Viam>);

  @override
  _i9.Future<bool> get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  set appAuth(_i3.FlutterAppAuth? _appAuth) => super.noSuchMethod(
    Invocation.setter(#appAuth, _appAuth),
    returnValueForMissingStub: null,
  );

  @override
  set secureStorage(_i4.FlutterSecureStorage? _secureStorage) =>
      super.noSuchMethod(
        Invocation.setter(#secureStorage, _secureStorage),
        returnValueForMissingStub: null,
      );

  @override
  set isConnectionError(bool? _isConnectionError) => super.noSuchMethod(
    Invocation.setter(#isConnectionError, _isConnectionError),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<bool> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> refreshConnection() =>
      (super.noSuchMethod(
            Invocation.method(#refreshConnection, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> loginAction() =>
      (super.noSuchMethod(
            Invocation.method(#loginAction, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logoutAction() =>
      (super.noSuchMethod(
            Invocation.method(#logoutAction, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [FlutterAppAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterAppAuth extends _i1.Mock implements _i3.FlutterAppAuth {
  MockFlutterAppAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.AuthorizationTokenResponse> authorizeAndExchangeCode(
    _i3.AuthorizationTokenRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authorizeAndExchangeCode, [request]),
            returnValue: _i9.Future<_i3.AuthorizationTokenResponse>.value(
              _FakeAuthorizationTokenResponse_23(
                this,
                Invocation.method(#authorizeAndExchangeCode, [request]),
              ),
            ),
          )
          as _i9.Future<_i3.AuthorizationTokenResponse>);

  @override
  _i9.Future<_i3.AuthorizationResponse> authorize(
    _i3.AuthorizationRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authorize, [request]),
            returnValue: _i9.Future<_i3.AuthorizationResponse>.value(
              _FakeAuthorizationResponse_24(
                this,
                Invocation.method(#authorize, [request]),
              ),
            ),
          )
          as _i9.Future<_i3.AuthorizationResponse>);

  @override
  _i9.Future<_i3.TokenResponse> token(_i3.TokenRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#token, [request]),
            returnValue: _i9.Future<_i3.TokenResponse>.value(
              _FakeTokenResponse_25(this, Invocation.method(#token, [request])),
            ),
          )
          as _i9.Future<_i3.TokenResponse>);

  @override
  _i9.Future<_i3.EndSessionResponse> endSession(
    _i3.EndSessionRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#endSession, [request]),
            returnValue: _i9.Future<_i3.EndSessionResponse>.value(
              _FakeEndSessionResponse_26(
                this,
                Invocation.method(#endSession, [request]),
              ),
            ),
          )
          as _i9.Future<_i3.EndSessionResponse>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i4.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_27(this, Invocation.getter(#iOptions)),
          )
          as _i4.IOSOptions);

  @override
  _i4.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_28(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i4.AndroidOptions);

  @override
  _i4.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_29(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i4.LinuxOptions);

  @override
  _i4.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_30(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i4.WindowsOptions);

  @override
  _i4.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_31(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i4.WebOptions);

  @override
  _i4.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_32(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i4.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i14.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i14.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> write({
    required String? key,
    required String? value,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> read({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<bool> containsKey({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> delete({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<Map<String, String>> readAll({
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i9.Future<Map<String, String>>);

  @override
  _i9.Future<void> deleteAll({
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i9.Future<bool?>.value(),
          )
          as _i9.Future<bool?>);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i15.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String?> getStoredOrg(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getStoredOrg, [userId]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> setSelectedOrg(String? userId, String? orgId) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedOrg, [userId, orgId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [Viam].
///
/// See the documentation for Mockito's code generation for more information.
class MockViam extends _i1.Mock implements _i6.Viam {
  MockViam() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.AppClient get appClient =>
      (super.noSuchMethod(
            Invocation.getter(#appClient),
            returnValue: _FakeAppClient_33(this, Invocation.getter(#appClient)),
          )
          as _i7.AppClient);

  @override
  _i6.AppRobotClient get appRobotClient =>
      (super.noSuchMethod(
            Invocation.getter(#appRobotClient),
            returnValue: _FakeAppRobotClient_34(
              this,
              Invocation.getter(#appRobotClient),
            ),
          )
          as _i6.AppRobotClient);

  @override
  _i8.BillingClient get billingClient =>
      (super.noSuchMethod(
            Invocation.getter(#billingClient),
            returnValue: _FakeBillingClient_35(
              this,
              Invocation.getter(#billingClient),
            ),
          )
          as _i8.BillingClient);

  @override
  _i6.DataClient get dataClient =>
      (super.noSuchMethod(
            Invocation.getter(#dataClient),
            returnValue: _FakeDataClient_36(
              this,
              Invocation.getter(#dataClient),
            ),
          )
          as _i6.DataClient);

  @override
  _i6.ProvisioningClient get provisioningClient =>
      (super.noSuchMethod(
            Invocation.getter(#provisioningClient),
            returnValue: _FakeProvisioningClient_37(
              this,
              Invocation.getter(#provisioningClient),
            ),
          )
          as _i6.ProvisioningClient);

  @override
  _i9.Future<_i6.RobotClient> getRobotClient(_i2.Robot? robot) =>
      (super.noSuchMethod(
            Invocation.method(#getRobotClient, [robot]),
            returnValue: _i9.Future<_i6.RobotClient>.value(
              _FakeRobotClient_38(
                this,
                Invocation.method(#getRobotClient, [robot]),
              ),
            ),
          )
          as _i9.Future<_i6.RobotClient>);
}

/// A class which mocks [ViamAppRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamAppRepository extends _i1.Mock implements _i16.ViamAppRepository {
  MockViamAppRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i2.LocationSummary>> get locationSummariesStream =>
      (super.noSuchMethod(
            Invocation.getter(#locationSummariesStream),
            returnValue: _i9.Stream<List<_i2.LocationSummary>>.empty(),
          )
          as _i9.Stream<List<_i2.LocationSummary>>);

  @override
  _i9.Stream<_i2.Organization?> get selectedOrganizationStream =>
      (super.noSuchMethod(
            Invocation.getter(#selectedOrganizationStream),
            returnValue: _i9.Stream<_i2.Organization?>.empty(),
          )
          as _i9.Stream<_i2.Organization?>);

  @override
  bool get hasSelectedOrg =>
      (super.noSuchMethod(
            Invocation.getter(#hasSelectedOrg),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Future<_i6.Viam> get viam =>
      (super.noSuchMethod(
            Invocation.getter(#viam),
            returnValue: _i9.Future<_i6.Viam>.value(
              _FakeViam_22(this, Invocation.getter(#viam)),
            ),
          )
          as _i9.Future<_i6.Viam>);

  @override
  set locationSummaries(List<_i2.LocationSummary>? _locationSummaries) =>
      super.noSuchMethod(
        Invocation.setter(#locationSummaries, _locationSummaries),
        returnValueForMissingStub: null,
      );

  @override
  set selectedOrg(_i2.Organization? _selectedOrg) => super.noSuchMethod(
    Invocation.setter(#selectedOrg, _selectedOrg),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateMachineSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#updateMachineSummaries, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.Organization?> getStoredOrg() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredOrg, []),
            returnValue: _i9.Future<_i2.Organization?>.value(),
          )
          as _i9.Future<_i2.Organization?>);

  @override
  _i9.Future<_i2.Organization> getSelectedOrg() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedOrg, []),
            returnValue: _i9.Future<_i2.Organization>.value(
              _FakeOrganization_0(this, Invocation.method(#getSelectedOrg, [])),
            ),
          )
          as _i9.Future<_i2.Organization>);

  @override
  _i9.Future<void> setSelectedOrg(_i2.Organization? org) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedOrg, [org]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearStoredVariables() =>
      (super.noSuchMethod(
            Invocation.method(#clearStoredVariables, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> checkLoginState() =>
      (super.noSuchMethod(
            Invocation.method(#checkLoginState, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> loginAction() =>
      (super.noSuchMethod(
            Invocation.method(#loginAction, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.LocationSummary>> listMachineSummaries(
    String? organizationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listMachineSummaries, [organizationId]),
            returnValue: _i9.Future<List<_i2.LocationSummary>>.value(
              <_i2.LocationSummary>[],
            ),
          )
          as _i9.Future<List<_i2.LocationSummary>>);

  @override
  _i9.Future<_i2.Organization> getOrganization(String? organizationId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganization, [organizationId]),
            returnValue: _i9.Future<_i2.Organization>.value(
              _FakeOrganization_0(
                this,
                Invocation.method(#getOrganization, [organizationId]),
              ),
            ),
          )
          as _i9.Future<_i2.Organization>);

  @override
  _i9.Future<_i2.Robot> getRobot(String? robotId) =>
      (super.noSuchMethod(
            Invocation.method(#getRobot, [robotId]),
            returnValue: _i9.Future<_i2.Robot>.value(
              _FakeRobot_5(this, Invocation.method(#getRobot, [robotId])),
            ),
          )
          as _i9.Future<_i2.Robot>);

  @override
  _i9.Future<_i2.Location> getLocation(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocation, [locationId]),
            returnValue: _i9.Future<_i2.Location>.value(
              _FakeLocation_3(
                this,
                Invocation.method(#getLocation, [locationId]),
              ),
            ),
          )
          as _i9.Future<_i2.Location>);

  @override
  _i9.Future<List<_i2.Organization>> listOrganizations() =>
      (super.noSuchMethod(
            Invocation.method(#listOrganizations, []),
            returnValue: _i9.Future<List<_i2.Organization>>.value(
              <_i2.Organization>[],
            ),
          )
          as _i9.Future<List<_i2.Organization>>);

  @override
  _i9.Future<List<_i2.Location>> listLocations([String? organizationId]) =>
      (super.noSuchMethod(
            Invocation.method(#listLocations, [organizationId]),
            returnValue: _i9.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i9.Future<List<_i2.Location>>);

  @override
  _i9.Future<List<_i2.Robot>> listRobots(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#listRobots, [locationId]),
            returnValue: _i9.Future<List<_i2.Robot>>.value(<_i2.Robot>[]),
          )
          as _i9.Future<List<_i2.Robot>>);

  @override
  _i9.Future<List<_i2.RobotPart>> listRobotParts(String? robotId) =>
      (super.noSuchMethod(
            Invocation.method(#listRobotParts, [robotId]),
            returnValue: _i9.Future<List<_i2.RobotPart>>.value(
              <_i2.RobotPart>[],
            ),
          )
          as _i9.Future<List<_i2.RobotPart>>);

  @override
  _i9.Future<void> updateRobotPart(
    String? robotPartId,
    String? name,
    Map<String, dynamic>? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRobotPart, [robotPartId, name, config]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateLocation({
    required String? locationId,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [], {
              #locationId: locationId,
              #name: name,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteRobot(String? robotId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRobot, [robotId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.Location> createLocation({
    required String? organizationId,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLocation, [], {
              #organizationId: organizationId,
              #name: name,
            }),
            returnValue: _i9.Future<_i2.Location>.value(
              _FakeLocation_3(
                this,
                Invocation.method(#createLocation, [], {
                  #organizationId: organizationId,
                  #name: name,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.Location>);

  @override
  _i9.Future<void> log(
    String? partId,
    String? host,
    String? loggerName,
    _i17.OutputEvent? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#log, [partId, host, loggerName, event]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> newMachine({
    required String? name,
    required String? locationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#newMachine, [], {
              #name: name,
              #locationId: locationId,
            }),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#newMachine, [], {
                  #name: name,
                  #locationId: locationId,
                }),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<({String email, String token})> getTokenAndEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getTokenAndEmail, []),
            returnValue: _i9.Future<({String email, String token})>.value((
              email: _i10.dummyValue<String>(
                this,
                Invocation.method(#getTokenAndEmail, []),
              ),
              token: _i10.dummyValue<String>(
                this,
                Invocation.method(#getTokenAndEmail, []),
              ),
            )),
          )
          as _i9.Future<({String email, String token})>);

  @override
  _i9.Future<_i2.RobotPart> getRobotPart(String? partId) =>
      (super.noSuchMethod(
            Invocation.method(#getRobotPart, [partId]),
            returnValue: _i9.Future<_i2.RobotPart>.value(
              _FakeRobotPart_6(
                this,
                Invocation.method(#getRobotPart, [partId]),
              ),
            ),
          )
          as _i9.Future<_i2.RobotPart>);

  @override
  _i9.Future<T> makeRequestWithRetry<T>(
    _i9.Future<T> Function()? request, {
    int? maxRetries = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #makeRequestWithRetry,
              [request],
              {#maxRetries: maxRetries},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #makeRequestWithRetry,
                      [request],
                      {#maxRetries: maxRetries},
                    ),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_39<T>(
                  this,
                  Invocation.method(
                    #makeRequestWithRetry,
                    [request],
                    {#maxRetries: maxRetries},
                  ),
                ),
          )
          as _i9.Future<T>);
}
