include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false
    directives_ordering: true
    prefer_relative_imports: true

analyzer:
  exclude:
    - '**/*.mocks.dart'
  errors:
    override_on_non_overriding_member: ignore